### ISSUE TITLE
Panic and stuck at #[EB|LOG:EXITBS:START]

### ISSUE THREAD

**Issue by vicshacks** [Lorys89/DELL_VOSTRO_5490#2]
Hi, I've been trying out this EFI on a Dell Vostro 5590 (exactly the same specs as the one in this repo) but I've had no luck.
I went and made all the changes in the BIOS, including CFG Lock and DVMT 64MB with RU.efi (CFG Lock is correctly disabled, as it's showing "0" on the OpenCore logs).
But after selecting the macOS installer on the OC picker and after around 1.5mins of verbose I get a panic. (The logs stop at the usual #[EB|LOG:EXITBS:START]).
I've tried switching out the USB stick, reverting the DVMT change in RU.efi and instead adding the framebuffer patches from the Dortania guide, I've tried both a Monterey and a Ventura recovery image, with the same result.
The only change I made to the config is enabling logs (a few properties in Misc/Debug).

here are the logs and a picture of the panic screen.
thx for any help
![IMG_2961](https://user-images.githubusercontent.com/84540693/215154680-fbf89ce0-0c58-455e-b875-b5ccc2e676ab.jpg)
[opencore-2023-01-27-181315.txt](https://github.com/Lorys89/DELL_VOSTRO_5490/files/10521476/opencore-2023-01-27-181315.txt)

**Comment by Lorys89** [comment]
Look at what model of nvme you have, you see it from windows in device manager

**Comment by vicshacks** [comment]
Micron 2200S 512GB
yeah i just googled it and it turns out it's uncompatible :/
though i had already been planning on buying another 512GB internal SSD, so that's what i'll do
Thanks and sorry lol

**Comment by Lorys89** [comment]
Ok, Get a compatible nvme 👍

**Comment by vicshacks** [comment]
hey i was wondering, does the vostro 5590 have a free SSD slot, so i can just add a 512gb drive, or does it only have a single slot, so i have to remove the pre-installed windows one and replace it?

**Comment by Lorys89** [comment]
1slot nvme, 1 slot ssd sata 2,5
